boonbooth:
  title: BoonBooth Loves you !
  background: "src/main/resources/fond_neutre.mp4"
  scene:
    width: 1280
    height: 720
  webcam:
    size: 0.60
  text:
    font: "/TheFrightHouseDEMO.otf"
    size: 160
    value: BoonBooth